### ISSUE TITLE
Не устанавливается статус заказа checkout complete.

### ISSUE THREAD

**Issue by sumerian-1** [yandex-money/yandex-money-cms-drupal#12]
Кажется, что модуль должен по-хорошему устанавливать статус заказа checkout complete после успешной оплаты. А он этого не далеат. Соответвенно, не срабатывают правила Rules, связанные с этим событием: отправка письма покупателю и админу, создание пользователя при анонимном заказе.

**Comment by ikarmanov** [comment]
Добрый день.

Занимаемся проверкой.

**Comment by shumod** [comment]
Возникла такая же ошибка. Оплата прошла, но статус заказа не выставляется.

**Comment by superromeo** [comment]
То же самое. 
Принимаю оплату на ЯД (работаю без договора с кассой).

**Comment by shumod** [comment]
решение тут http://dru.io/question/1910

**Comment by sumerian-1** [comment]
shumod, это не решение, а воркараунд. Я тоже так сделал. Но это не совсем правильно, модуль должен устанавливать статус checkout complete, как это делают другие подобные.

**Comment by superromeo** [comment]
Событие "When an order is first paid in full" вообще не происходит. Статус заказа так и остаётся "Оформление заказа: Оплата".

**Comment by superromeo** [comment]
Яндекс забил на нас.

**Comment by ostulov** [comment]
Добрый день!

Смена статуса заказа также зависит от настроек на стороне Яндекс.Кассы или Яндекс.Денег. Если у Вас наблюдается проблема со сменой статусов, Вам необходимо обратиться в техподдержку соответствующего сервиса для сверки настроек.
