### ISSUE TITLE
Добавить возможность приёма доплаты

### ISSUE THREAD

**Issue by witwar** [yandex-money/yandex-money-cms-drupal#16]
Текущая логика модуля такова, что платёж должен происходить за один раз. Но так происходит не всегда. Вот пример из реальной жизни:
1. клиент делает заказ и переходит к оплате
2. клиент выбирает оплату через терминал и получает код
3. клиент оплачивает заказ в терминале и платёж проходит, но из-за комиссии терминала денег для оплаты заказа не хватает
4. клиент доплачивает недостающую сумму и она принимается терминалом и яндекс.кассой, но в магазин она уже не доходит

Происходит это из-за того, что после первого платежа транзакция получает статус 'processed' и приём платежей становится не возможным.

Разобраться с проблемой можно вручную (например, изменить статус транзакции в базе друпала или создать новый заказ и произвести доплату небольшой суммы), но хотелось бы видеть функционал для доплаты в модуле...

**Comment by ikarmanov** [comment]
Добрый день.

Сервис Яндекс.Касса отправляет уведомления об оплате только после достижения полной суммы заказа. Если у Вас есть пример такой транзакции, то прошу Вас написать на cms@yamoney.ru.
