### ISSUE TITLE
Где картинки?

### ISSUE THREAD

**Issue by OnkelTem** [yandex-money/yandex-money-cms-drupal#2]
Модуль ссылается на картинки, но их просто нет в нем.

![Хром](https://sc-cdn.scaleengine.net/i/ad38fa73d64c5b4a3975e8792cbb0f8d.png)

![Drupal](https://sc-cdn.scaleengine.net/i/25bc3a36df3a53021aae7f9316d870e4.png)

**Comment by ikarmanov** [comment]
Добрый день.
Спасибо за замечание. Изображения добавлены.

**Comment by OnkelTem** [comment]
Отлично, связь налажена!
