### ISSUE TITLE
портирование для drupal 8

### ISSUE THREAD

**Issue by redikz** [yandex-money/yandex-money-cms-drupal#20]
Оочень хочется видеть такой модуль на drupal 8. для рунета, на мой взгляд, самый лучший вариант. 
Планируется ли проведение работ по портированию?

**Comment by ikarmanov** [comment]
Добрый день.

Мы рассматриваем такой вариант, но по времени выхода сказать затрудняюсь.

**Comment by ostulov** [comment]
https://github.com/yandex-money/yandex-money-cms-v2-drupal8
