### ISSUE TITLE
Ошибка Notice: Undefined index: 0 в функции yamoney_admin_settings_validate()

### ISSUE THREAD

**Issue by andrey-kustyshev** [yandex-money/yandex-money-cms-drupal#26]
При настройке в админке выскакивает:

Notice: Undefined index: 0 в функции yamoney_admin_settings_validate() (строка 352 в файле .../sites/all/modules/yandex-money-cms-drupal-master/yamoney.admin.inc).

(Drupal Commerce)

**Comment by ostulov** [comment]
Данная проблема была исправлена в следующей версии модуля.
