### ISSUE TITLE
Не сохраняется секретное слово в настройках Яндекс-кассы

### ISSUE THREAD

**Issue by andrey-kustyshev** [yandex-money/yandex-money-cms-drupal#27]
При сохранении настроек во вкладке Яндекс-касса, поле "Скретное слово" не сохраняется (в таблице Variable поле yamoney_secret пустое).

Я посмотрел форму и в ней есть два одинаковых поля "yamoney_secret"
Одно во вкладке $form['yamoney_p2p_tab']
Другое в $form['yamoney_kassa_tab']
Которые пишут данные в одну и ту же переменную 

Проблема решается если заполнить поле во вкладке "Яндекс-деньги"
Но до этого еще догадаться надо....

**Comment by ikarmanov** [comment]
Добрый день.

Спасибо за информацию. Проверяем.

**Comment by demozzzzz** [comment]
столкнулся с аналогичной проблемой, добавьте в мануал данный пункт

**Comment by andrey-kustyshev** [comment]
Тут Яндекс на все забил. (последнее обновление 2 месяца назад)
