### ISSUE TITLE
Ошибка Notice: A non well formed numeric value encountered

### ISSUE THREAD

**Issue by andrey-kustyshev** [yandex-money/yandex-money-cms-drupal#28]
Во время оплаты выскакивает

Notice: A non well formed numeric value encountered в функции ya_commerce_redirect_form() (строка 215 в файле ../sites/all/modules/yandex-money-cms-drupal-master/ya_commerce/ya_commerce.module)

(Drupal Commerce)

**Comment by ostulov** [comment]
Данная проблема была исправлена в следующей версии модуля.
