### ISSUE TITLE
Ошибка Notice: Undefined index: payment_method

### ISSUE THREAD

**Issue by andrey-kustyshev** [yandex-money/yandex-money-cms-drupal#29]
Если в админке указать способ оплаты "kassa mode", то появляется еще один нотис:
Notice: Undefined index: payment_method в функции ya_commerce_yamoney_shop_params_alter() (строка 281 в файле .../sites/all/modules/yandex-money-cms-drupal-master/ya_commerce/ya_commerce.module).

(Drupal Commerce)

**Comment by ostulov** [comment]
Данная проблема была исправлена в следующей версии модуля.
