### ISSUE TITLE
Критично: Неправильно формируется сумма в чеке для фискальной службы (Commerce)

### ISSUE THREAD

**Issue by andrey-kustyshev** [yandex-money/yandex-money-cms-drupal#30]
Есть такой кусок кода:
`'amount' => number_format(getPriceByData($product->commerce_price['und'][0]['amount'], $product->commerce_price['und'][0]['currency_code']), 2, '.', ''),`

**И вот что у нас происходит в этом коде:**

Реальная цена товара - **1560р. 45к.**
Переменная $product->commerce_price['und'][0]['amount'] хранит это как целое число **156045**

Мы сначала прогоняем это через **getPriceByData()**
В результате получаем строковую переменную типа **1.560,45** (внешний вид зависит от тех настроек, который задал пользователь в админке)

Потом код пытается привести это к нужному виду через  **number_format()**
Функция ругается на то, что ей подсовывают переменную не число, но при этом все равно выдает результат.

В моем случае до 1000 руб. ей удавалось выдать корректную сумму.
Выше тысячи получалось "1.00", и фискальная служба заворачивала чеки.

Я себе поправил так:
`'amount' => number_format($product->commerce_price['und'][0]['amount'] / 100, 2, '.', ''),`

**Comment by xandeadx** [comment]
https://github.com/yandex-money/yandex-money-cms-drupal/pull/33

**Comment by ikarmanov** [comment]
Добрый день.

Теперь проблема устранена в 1.4.2
