### ISSUE TITLE
Поддержка скидок

### ISSUE THREAD

**Issue by andrey-kustyshev** [yandex-money/yandex-money-cms-drupal#36]
В данный момент если заказ имеет скидку, то сумма фискального чека не сходится с суммой заказа. Из-за этого происходит отказ платежа.

**Comment by ostulov** [comment]
Добрый день!

Проверьте, что у Вас установлена последняя версия модуля. Если проблема возникает с последней версией модуля, то напишите нам письмо с подробностями на почту cms@yamoney.ru
