### ISSUE TITLE
После оплаты, в админке не меняется статус заказа на "оплачено"

### ISSUE THREAD

**Issue by DexColt** [yandex-money/yandex-money-cms-drupal#39]
Не понятно какие заказы оплачены, так как у всех стоит статус "в ожидании", по факту платеж прошел.

**Comment by ostulov** [comment]
Смена статуса заказа зависит от настроек, заданных на стороне Яндекс.Кассы. Для уточнения причины, почему статус заказа не меняется, необходимо обратиться в службу поддержки Яндекс.Кассы.
