### ISSUE TITLE
При переходе переходе на яндекс для оплаты, вылетает непонятная ошибка.

### ISSUE THREAD

**Issue by DexColt** [yandex-money/yandex-money-cms-drupal#40]
После выбора яндекса, как методом оплаты и переходе на сторону оплаты для ввода данных, перед редиректом пользователю показывается ошибка:

Notice: Undefined index: payment_method in function ya_commerce_yamoney_shop_params_alter() (String 404 in file modules/yandex-money-cms-drupal-1.4.3/ya_commerce/ya_commerce.module)

**Comment by ostulov** [comment]
Добрый день!

Для разбора данной проблемы напишите письмо на почту cms@yamoney с приложением подробной информации о возникающей проблеме, доступами в админпанель сайта и к ftp.
