### ISSUE TITLE
Notice: Uninitialized string offset: 0 в функции yamoney_admin_settings

### ISSUE THREAD

**Issue by kratkar** [yandex-money/yandex-money-cms-drupal#9]
Drupal 7.37 Ubercart 3.8. Установил первый раз и перешел на страницу настройки `/admin/config/system/yamoney`, а там:
`Notice: Uninitialized string offset: 0 в функции yamoney_admin_settings() (строка 112 в файле .../sites/all/modules/yandex-money-cms-drupal/yamoney.admin.inc).`
Так же строки 113, 119, 120.
Не ошибка, но моё дело сообщить.

**Comment by kratkar** [comment]
Я всегда проверяю
```php
isset($success['value'])
```
Ваш К.О.)

**Comment by ikarmanov** [comment]
Добрый день.

Спасибо за информацию. В следующих версиях модуля исправим.
